name: Nightly Flow

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  schedule:
    - cron: "20 20 * * *"
  workflow_dispatch:
    inputs:
      skipjobs:
        description: 'jobs to skip (delete the ones you wanna keep, do not leave empty)'
        default: 'valgrind,sanitizer,tls,freebsd,macos,alpine,32bit,iothreads,ubuntu,centos,malloc,specific,fortify,reply-schema,oldTC'
      skiptests:
        description: 'tests to skip (delete the ones you wanna keep, do not leave empty)'
        default: 'redis,modules,sentinel,cluster,unittest'
      test_args:
        description: 'extra test arguments'
        default: ''
      cluster_test_args:
        description: 'extra cluster / sentinel test arguments'
        default: ''
      use_repo:
        description: 'repo owner and name'
        default: 'redis/redis'
      use_git_ref:
        description: 'git branch or sha to use'
        default: 'unstable'

# TODO: Use RedisJSON's `master` branch when testing on nightly

jobs:
  sanitize:
    secrets: inherit
    uses: ./.github/workflows/task-test.yml
    with:
      get-redis: unstable
      test-config: QUICK=1
      san: address
      env: ubuntu-latest
      container: ubuntu:jammy
